id: P004287
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD88994
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༢༠༽
  author: ''
  volumes:
    a28d0b6f9a3146819650c0dcd729ee4e:
      image_group_id: I1PD89015
      title: ''
      volume_number: 1
      total_pages: 197
      base_file: v001.txt
