id: P004287
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:07:44.409070
source_metadata:
  id: bdr:W1PD88994
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་ཡིག ༼༢༠༽
  author: ''
  volumes:
    a28d0b6f9a3146819650c0dcd729ee4e:
      image_group_id: I1PD89015
      title: ''
      volume_number: 1
      total_pages: 197
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
